/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.PacienteDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import servicos.PacienteServicos;
import servicos.UsuarioServicos;

/**
 *
 * @author user
 */
public class GUIExcluirUsuario extends javax.swing.JInternalFrame {

    modelo.Paciente p = new modelo.Paciente();
    
    Vector<Integer> id_responsavel =  new Vector<Integer>();
    
    public void restaurarUsuarioCBX(){
        try{
            PacienteDao paciente = new PacienteDao();
            ResultSet rs = paciente.buscarResponsavel();
            
            while (rs.next()){
                id_responsavel.addElement(rs.getInt(1));
                cbxResponsavel.addItem(rs.getString(2));
            }
            
        }
        catch (SQLException e){
            
        }
    }
    
    public void finalizarUsuario(){
        try{
          UsuarioServicos us = servicos.ServicosFactory.getUsuarioServicos();
          Integer codUsuario = id_responsavel.get(cbxResponsavel.getSelectedIndex()-1);
          
          int r = JOptionPane.showConfirmDialog(null, "Você deseja excluir o usuário?","Confirmação",JOptionPane.INFORMATION_MESSAGE);
           if (r==JOptionPane.YES_OPTION){
               us.deletarUsuario(codUsuario);
               dispose();
               GUIExcluirUsuario.this.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null, "Exclusão Cancelada!","Confirmação",JOptionPane.INFORMATION_MESSAGE);
           }
        }
        
        catch (SQLException e){
            
        }
    }
    /**
     * Creates new form GUIExcluirUsuario
     */
    public GUIExcluirUsuario() {
        initComponents();
        restaurarUsuarioCBX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlExcluirUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbSim = new javax.swing.JButton();
        jbNao = new javax.swing.JButton();
        jlConfirmacao = new javax.swing.JLabel();
        cbxResponsavel = new javax.swing.JComboBox<>();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jlExcluirUsuario.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jlExcluirUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlExcluirUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExcluirUsuario.setText("EXCLUIR USUÁRIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlExcluirUsuario)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbSim.setText("Sim");
        jbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimActionPerformed(evt);
            }
        });

        jbNao.setText("Não");
        jbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNaoActionPerformed(evt);
            }
        });

        jlConfirmacao.setText("Gostaria de Excluir os dados do usuário?");

        cbxResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jbSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxResponsavel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlConfirmacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jlConfirmacao)
                .addGap(38, 38, 38)
                .addComponent(cbxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSim)
                    .addComponent(jbNao))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxResponsavelActionPerformed

    private void jbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimActionPerformed
        finalizarUsuario();
    }//GEN-LAST:event_jbSimActionPerformed

    private void jbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNaoActionPerformed
        dispose();
    }//GEN-LAST:event_jbNaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxResponsavel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbNao;
    private javax.swing.JButton jbSim;
    private javax.swing.JLabel jlConfirmacao;
    private javax.swing.JLabel jlExcluirUsuario;
    // End of variables declaration//GEN-END:variables
}
